/** Payment categories used across DMS billing. */
export const PAYMENT_TYPE_LABELS = {
  regular: "Regular",
  custodian: "Custodian",
  xray: "X-Ray",
  personal_portal: "Personal",
};

/**
 * Order-centric payment records. Replace with backend API when Stripe is integrated.
 */
export const ORDER_PAYMENT_DETAILS = {
  "24018": {
    orderId: "24018",
    orderNo: "24018",
    company: "Summit Legal Group",
    applicant: "Robert Martinez",
    caseNo: "WC-2024-1182",
    invoices: [
      {
        id: "inv-24018-reg",
        type: "regular",
        invoiceNo: "INV-24018",
        invoiceDate: "2026-04-15",
        lastSentDate: "2026-04-18",
        amount: 350.0,
        paid: 185.5,
        due: 164.5,
        status: "Partial",
      },
      {
        id: "inv-24018-cust",
        type: "custodian",
        invoiceNo: "INV-24018-C",
        invoiceDate: "2026-04-20",
        lastSentDate: "2026-04-22",
        amount: 75.0,
        paid: 0,
        due: 75.0,
        status: "Unpaid",
      },
    ],
    manualPayments: [
      {
        id: "m1",
        paymentDate: "2026-05-28",
        paymentType: "regular",
        invoiceNo: "INV-24018",
        amount: 185.5,
        method: "Check",
        referenceNo: "CHK-88421",
        recordedBy: "Sarah Chen",
        status: "Recorded",
        notes: "Partial payment applied to regular invoice",
      },
    ],
    onlinePayments: [],
  },
  "23994": {
    orderId: "23994",
    orderNo: "23994",
    company: "Harbor & Associates",
    applicant: "Lisa Thompson",
    caseNo: "WC-2024-1095",
    invoices: [
      {
        id: "inv-23994-reg",
        type: "regular",
        invoiceNo: "INV-23994",
        invoiceDate: "2026-04-01",
        lastSentDate: "2026-04-05",
        amount: 420.0,
        paid: 320.0,
        due: 100.0,
        status: "Partial",
      },
      {
        id: "inv-23994-xray",
        type: "xray",
        invoiceNo: "INV-23994-X",
        invoiceDate: "2026-04-12",
        lastSentDate: "2026-04-14",
        amount: 180.0,
        paid: 180.0,
        due: 0,
        status: "Paid",
      },
    ],
    manualPayments: [
      {
        id: "m2",
        paymentDate: "2026-05-22",
        paymentType: "regular",
        invoiceNo: "INV-23994",
        amount: 320.0,
        method: "Wire Transfer",
        referenceNo: "WIRE-99201",
        recordedBy: "Mike Johnson",
        status: "Recorded",
        notes: "Wire received for regular invoice balance",
      },
    ],
    onlinePayments: [
      {
        id: "o2b",
        transactionDate: "2026-05-24T11:30:00",
        paymentType: "xray",
        invoiceNo: "INV-23994-X",
        amount: 180.0,
        paymentMethod: "Card",
        status: "Succeeded",
        stripePaymentId: "pi_3PxJ8nLkdIwHu7ix1RmNc4b1",
        stripeChargeId: "ch_3PxJ8nLkdIwHu7ix1RmNc4b2",
        stripeCustomerId: "cus_Qk9mN2pLkdIwHu7",
        cardBrand: "Visa",
        cardLast4: "1881",
        cardExpMonth: 8,
        cardExpYear: 2028,
        customerEmail: "ap@coastalclaims.com",
        customerName: "Coastal Claims LLP",
        receiptUrl: "https://pay.stripe.com/receipts/example-23994",
        currency: "usd",
        processingFee: 5.52,
        netAmount: 174.48,
        failureMessage: null,
      },
    ],
  },
  "23971": {
    orderId: "23971",
    orderNo: "23971",
    company: "Pacific Injury Law",
    applicant: "David Kim",
    caseNo: "WC-2023-2204",
    invoices: [
      {
        id: "inv-23971-cust",
        type: "custodian",
        invoiceNo: "INV-23971-C",
        invoiceDate: "2026-03-28",
        lastSentDate: "2026-03-30",
        amount: 95.0,
        paid: 95.0,
        due: 0,
        status: "Paid",
      },
    ],
    manualPayments: [
      {
        id: "m3",
        paymentDate: "2026-05-15",
        paymentType: "custodian",
        invoiceNo: "INV-23971-C",
        amount: 95.0,
        method: "Cash",
        referenceNo: "CASH-0042",
        recordedBy: "Sarah Chen",
        status: "Recorded",
        notes: "Walk-in custodian fee payment",
      },
    ],
    onlinePayments: [],
  },
  "24031": {
    orderId: "24031",
    orderNo: "24031",
    company: "Summit Legal Group",
    applicant: "Angela Brooks",
    caseNo: "WC-2024-1210",
    invoices: [
      {
        id: "inv-24031-reg",
        type: "regular",
        invoiceNo: "INV-24031",
        invoiceDate: "2026-05-10",
        lastSentDate: "2026-05-12",
        amount: 410.75,
        paid: 210.75,
        due: 200.0,
        status: "Partial",
      },
    ],
    manualPayments: [
      {
        id: "m4",
        paymentDate: "2026-06-02",
        paymentType: "regular",
        invoiceNo: "INV-24031",
        amount: 210.75,
        method: "Check",
        referenceNo: "CHK-88502",
        recordedBy: "Mike Johnson",
        status: "Pending Review",
        notes: "Awaiting deposit confirmation",
      },
    ],
    onlinePayments: [],
  },
  "24025": {
    orderId: "24025",
    orderNo: "24025",
    company: "Northgate Attorneys",
    applicant: "James Wilson",
    caseNo: "WC-2024-1198",
    invoices: [
      {
        id: "inv-24025-reg",
        type: "regular",
        invoiceNo: "INV-24025",
        invoiceDate: "2026-05-01",
        lastSentDate: "2026-05-03",
        amount: 275.0,
        paid: 275.0,
        due: 0,
        status: "Paid",
      },
    ],
    manualPayments: [],
    onlinePayments: [
      {
        id: "o1",
        transactionDate: "2026-06-01T14:22:00",
        paymentType: "regular",
        invoiceNo: "INV-24025",
        amount: 275.0,
        paymentMethod: "Card",
        status: "Succeeded",
        stripePaymentId: "pi_3PxK2mLkdIwHu7ix0QZqF8a2",
        stripeChargeId: "ch_3PxK2mLkdIwHu7ix0QZqF8a3",
        stripeCustomerId: "cus_Pm4kL8nLkdIwHu7",
        cardBrand: "Visa",
        cardLast4: "4242",
        cardExpMonth: 12,
        cardExpYear: 2027,
        customerEmail: "billing@northgateattorneys.com",
        customerName: "Northgate Attorneys",
        receiptUrl: "https://pay.stripe.com/receipts/example-24025",
        currency: "usd",
        processingFee: 8.28,
        netAmount: 266.72,
        failureMessage: null,
      },
    ],
  },
  "24033": {
    orderId: "24033",
    orderNo: "24033",
    company: "Harbor & Associates",
    applicant: "Kevin O'Brien",
    caseNo: "WC-2024-1214",
    invoices: [
      {
        id: "inv-24033-reg",
        type: "regular",
        invoiceNo: "INV-24033",
        invoiceDate: "2026-05-18",
        lastSentDate: "2026-05-20",
        amount: 420.0,
        paid: 0,
        due: 420.0,
        status: "Unpaid",
      },
    ],
    manualPayments: [],
    onlinePayments: [
      {
        id: "o3",
        transactionDate: "2026-06-03T16:45:00",
        paymentType: "regular",
        invoiceNo: "INV-24033",
        amount: 420.0,
        paymentMethod: "ACH",
        status: "Pending",
        stripePaymentId: "pi_3PxM1pLkdIwHu7ix2TsPd5c3",
        stripeChargeId: null,
        stripeCustomerId: "cus_Rn2pM9kLkdIwHu7",
        cardBrand: null,
        cardLast4: null,
        cardExpMonth: null,
        cardExpYear: null,
        customerEmail: "payments@harborlaw.com",
        customerName: "Harbor & Associates",
        receiptUrl: null,
        currency: "usd",
        processingFee: 0,
        netAmount: 0,
        failureMessage: null,
        achBankName: "Chase",
        achLast4: "6789",
      },
    ],
  },
  "23988": {
    orderId: "23988",
    orderNo: "23988",
    company: "Pacific Injury Law",
    applicant: "Susan Lee",
    caseNo: "WC-2024-1088",
    invoices: [
      {
        id: "inv-23988-xray",
        type: "xray",
        invoiceNo: "INV-23988-X",
        invoiceDate: "2026-04-25",
        lastSentDate: "2026-04-27",
        amount: 98.5,
        paid: 0,
        due: 98.5,
        status: "Unpaid",
      },
    ],
    manualPayments: [],
    onlinePayments: [
      {
        id: "o4",
        transactionDate: "2026-05-20T11:05:00",
        paymentType: "xray",
        invoiceNo: "INV-23988-X",
        amount: 98.5,
        paymentMethod: "Card",
        status: "Failed",
        stripePaymentId: "pi_3PxG4qLkdIwHu7ix3UvQe6d4",
        stripeChargeId: null,
        stripeCustomerId: "cus_Sp7nQ1kLkdIwHu7",
        cardBrand: "Mastercard",
        cardLast4: "5556",
        cardExpMonth: 3,
        cardExpYear: 2026,
        customerEmail: "accounts@pacificinjurylaw.com",
        customerName: "Pacific Injury Law",
        receiptUrl: null,
        currency: "usd",
        processingFee: 0,
        netAmount: 0,
        failureMessage: "Your card was declined. Insufficient funds.",
      },
    ],
  },
};

/** @deprecated Kept for reference — data now lives in ORDER_PAYMENT_DETAILS */
export const MANUAL_PAYMENTS = [];
export const ONLINE_PAYMENTS = [];
